---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  "Creates an IAM role that allows the New Relic AWS account to read our resources"

Parameters:
  NewRelicAccountNumber:
    Type: String

Resources:
  NewRelicIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "NewRelicIntegrationRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::754728514883:root"
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref NewRelicAccountNumber

Outputs:
  NewRelicRoleArn:
    Description: ARN of the created IAM role
    Value: !GetAtt [NewRelicIntegrationRole, Arn]
